"""init

Revision ID: 5f56829b0433
Revises: 
Create Date: 2025-06-12 18:57:43.747705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f56829b0433'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('keyword')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nombre', sa.VARCHAR(length=255), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=255), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=100), nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
